import { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.css'
import React from 'react'

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal', 'italic']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang='en'>
      <body className={notoSans.variable}>{children}</body>
    </html>
  )
}

export default RootLayout
