name: Lerna Changed
on:
  push:
    branches:
      - main

jobs:
  changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - name: Check for changed packages
        id: changes
        run: |
          latest_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $latest_tag"
          changed=$(bun x lerna changed --json || echo "[]")
          echo "$changed"
          echo "packages=$changed" >> "$GITHUB_OUTPUT"

      - name: Dry run publish
        if: steps.changes.outputs.packages != '[]'
        run: bun x lerna publish --yes --no-private --dry-run

