name: Lerna Publish Check
on:
  push:
    branches:
      - main

jobs:
  changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - name: Install jq
        run: which jq || (sudo apt-get update && sudo apt-get install -y jq)
      - name: Check for changed packages
        id: changes
        run: |
          latest_tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))
          echo "Latest tag: $latest_tag"
          changed=$(bun x lerna changed --json 2>error.log)
          if [ $? -eq 0 ]; then
            echo "$changed"
          elif grep -q "No changed packages found" error.log; then
            echo "[]"
            changed="[]"
          else
            echo "Error running 'lerna changed':"
            cat error.log
            exit 1
          fi
          # Determine whether any packages changed using jq for reliability
          has_changes=$(echo "$changed" | jq 'length > 0')
          echo "has_changes=$has_changes" >> "$GITHUB_OUTPUT"

      - name: Clean branch with hard reset
        run: |
          git fetch origin
          git reset --hard origin/main
          echo "Performed hard reset to ensure clean branch state"

      - name: Configure npm for publish
        if: steps.changes.outputs.has_changes == 'true'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm set registry https://registry.npmjs.org/
          npm set scope @geocaching
          npm set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: Dry run publish
        id: dry_run
        if: steps.changes.outputs.has_changes == 'true'
        env:
          NPM_CONFIG_DRY_RUN: 'true'
        run: bun x lerna publish from-package --yes --no-private --loglevel info

      - name: Publish packages
        if: steps.changes.outputs.has_changes == 'true' && steps.dry_run.outcome == 'success'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bun x lerna publish from-package --yes --no-private --ignore-scripts --loglevel info
