name: Publish Dry Run

on:
  push:
    branches: [main]

jobs:
  publish_dry_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: ${{ runner.os }}-bun-
      - run: bun install
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - id: detect_changes
        run: |
          CHANGED=$(bun x lerna changed --json --loglevel silent || echo "[]")
          COUNT=$(echo "$CHANGED" | jq 'length')
          echo "count=$COUNT" >> "$GITHUB_OUTPUT"
      - name: Build packages
        if: ${{ steps.detect_changes.outputs.count != '0' }}
        run: bun x lerna run build
      - name: Publish dry run
        if: ${{ steps.detect_changes.outputs.count != '0' }}
        env:
          NPM_CONFIG_DRY_RUN: 'true'
        run: bun x lerna publish from-package --yes --no-private --loglevel info --ignore-scripts
      - name: Publish packages
        if: ${{ steps.detect_changes.outputs.count != '0' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: https://registry.npmjs.org
        run: bun x lerna publish from-package --yes --no-private --loglevel info --ignore-scripts --registry https://registry.npmjs.org
